// NeetCode 150 catalog.
// Each item: [slug, title, difficulty, optimal approach, time complexity, space complexity]
// Slugs match leetcode.com/problems/<slug>/ where the problem exists on LeetCode.
const DATA = [
["Arrays & Hashing", [
  ["contains-duplicate", "Contains Duplicate", "E",
    "Add each number to a hash set; if a number is already in the set, a duplicate exists.", "O(n)", "O(n)"],
  ["valid-anagram", "Valid Anagram", "E",
    "Count character frequencies of s, then subtract while scanning t; any count that goes missing fails.", "O(n)", "O(1)"],
  ["two-sum", "Two Sum", "E",
    "One pass with a hash map: for each number, look up target − n among the numbers seen so far, then store it.", "O(n)", "O(n)"],
  ["group-anagrams", "Group Anagrams", "M",
    "Bucket words in a hash map keyed by their 26-letter count signature — anagrams share the same key.", "O(n·k)", "O(n·k)"],
  ["top-k-frequent-elements", "Top K Frequent Elements", "M",
    "Count frequencies, then bucket-sort by count (index = frequency) and read buckets from high to low.", "O(n)", "O(n)"],
  ["encode-and-decode-strings", "Encode and Decode Strings", "M",
    "Prefix each string with its length and a delimiter (\"4#word\") so decoding is unambiguous for any characters.", "O(n)", "O(n)"],
  ["product-of-array-except-self", "Product of Array Except Self", "M",
    "Two passes writing into the output: multiply in running prefix products left→right, then running suffix products right→left.", "O(n)", "O(1)"],
  ["valid-sudoku", "Valid Sudoku", "M",
    "One scan tracking seen digits per row, per column, and per 3×3 box with hash sets.", "O(81)", "O(81)"],
  ["longest-consecutive-sequence", "Longest Consecutive Sequence", "M",
    "Put all numbers in a set; only start counting a run from numbers whose left neighbor (n−1) is absent.", "O(n)", "O(n)"],
]],
["Two Pointers", [
  ["valid-palindrome", "Valid Palindrome", "E",
    "Two pointers from both ends, skipping non-alphanumeric characters and comparing lowercased characters.", "O(n)", "O(1)"],
  ["two-sum-ii-input-array-is-sorted", "Two Sum II - Input Array Is Sorted", "M",
    "Two pointers on the sorted array: move left up if the sum is too small, right down if too big.", "O(n)", "O(1)"],
  ["3sum", "3Sum", "M",
    "Sort, fix each first element, then run the two-pointer Two Sum II on the remainder, skipping duplicates.", "O(n²)", "O(1)"],
  ["container-with-most-water", "Container With Most Water", "M",
    "Two pointers at the ends; always move the shorter line inward, since it is what limits the area.", "O(n)", "O(1)"],
  ["trapping-rain-water", "Trapping Rain Water", "H",
    "Two pointers tracking leftMax / rightMax; the smaller side's max bounds the water above that pointer.", "O(n)", "O(1)"],
]],
["Sliding Window", [
  ["best-time-to-buy-and-sell-stock", "Best Time to Buy and Sell Stock", "E",
    "Sliding window: track the cheapest price seen so far (buy) and the best profit selling at each later day.", "O(n)", "O(1)"],
  ["longest-substring-without-repeating-characters", "Longest Substring Without Repeating Characters", "M",
    "Grow a window to the right; on a repeat, shrink from the left until the window is unique again.", "O(n)", "O(m)"],
  ["longest-repeating-character-replacement", "Longest Repeating Character Replacement", "M",
    "A window is valid while (window length − max letter count) ≤ k; expand right, slide left when invalid.", "O(n)", "O(26)"],
  ["permutation-in-string", "Permutation in String", "M",
    "Slide a fixed-size window over s2, comparing 26-letter counts against s1's counts incrementally.", "O(n)", "O(26)"],
  ["minimum-window-substring", "Minimum Window Substring", "H",
    "Expand right until all of t is covered, then shrink left greedily while coverage still holds; track the best window.", "O(n)", "O(m)"],
  ["sliding-window-maximum", "Sliding Window Maximum", "H",
    "Monotonic decreasing deque of indices; the front is always the current window's maximum.", "O(n)", "O(k)"],
]],
["Stack", [
  ["valid-parentheses", "Valid Parentheses", "E",
    "Push opening brackets on a stack; each closing bracket must match the top, and the stack must end empty.", "O(n)", "O(n)"],
  ["min-stack", "Min Stack", "M",
    "Store (value, min-so-far) pairs on the stack so getMin is just a peek at the top.", "O(1) per op", "O(n)"],
  ["evaluate-reverse-polish-notation", "Evaluate Reverse Polish Notation", "M",
    "Push numbers on a stack; on an operator, pop two operands, apply it, and push the result.", "O(n)", "O(n)"],
  ["generate-parentheses", "Generate Parentheses", "M",
    "Backtracking: add '(' while opens remain, add ')' only while it keeps the string balanced.", "O(4ⁿ/√n)", "O(n)"],
  ["daily-temperatures", "Daily Temperatures", "M",
    "Monotonic decreasing stack of indices; a warmer day pops and resolves every colder day waiting on the stack.", "O(n)", "O(n)"],
  ["car-fleet", "Car Fleet", "M",
    "Sort cars by position descending; a car merges into the fleet ahead if its arrival time is not later.", "O(n log n)", "O(n)"],
  ["largest-rectangle-in-histogram", "Largest Rectangle in Histogram", "H",
    "Monotonic increasing stack; popping a taller bar fixes the maximal-width rectangle it can span.", "O(n)", "O(n)"],
]],
["Binary Search", [
  ["binary-search", "Binary Search", "E",
    "Classic halving: compare the middle element to the target and discard half the range each step.", "O(log n)", "O(1)"],
  ["search-a-2d-matrix", "Search a 2D Matrix", "M",
    "Treat the matrix as one sorted array of m·n cells and binary search over flat indices.", "O(log mn)", "O(1)"],
  ["koko-eating-bananas", "Koko Eating Bananas", "M",
    "Binary search the answer (eating speed); feasibility is a simple sum of ceiling divisions.", "O(n log m)", "O(1)"],
  ["find-minimum-in-rotated-sorted-array", "Find Minimum in Rotated Sorted Array", "M",
    "Binary search: if nums[mid] > nums[right] the minimum lies right of mid, otherwise at mid or left.", "O(log n)", "O(1)"],
  ["search-in-rotated-sorted-array", "Search in Rotated Sorted Array", "M",
    "Binary search deciding which half is sorted and whether the target lies inside that half.", "O(log n)", "O(1)"],
  ["time-based-key-value-store", "Time Based Key-Value Store", "M",
    "Per key, append (timestamp, value) in order; get() binary searches for the rightmost timestamp ≤ query.", "O(log n)", "O(n)"],
  ["median-of-two-sorted-arrays", "Median of Two Sorted Arrays", "H",
    "Binary search the partition point of the smaller array so both left halves ≤ both right halves.", "O(log min(m,n))", "O(1)"],
]],
["Linked List", [
  ["reverse-linked-list", "Reverse Linked List", "E",
    "Walk the list once, flipping each node's next pointer to point at the previous node.", "O(n)", "O(1)"],
  ["merge-two-sorted-lists", "Merge Two Sorted Lists", "E",
    "Dummy head; repeatedly attach the smaller front node of the two lists and advance that list.", "O(n+m)", "O(1)"],
  ["linked-list-cycle", "Linked List Cycle", "E",
    "Floyd's tortoise & hare: fast moves 2, slow moves 1; they meet if and only if a cycle exists.", "O(n)", "O(1)"],
  ["reorder-list", "Reorder List", "M",
    "Find the middle (slow/fast), reverse the second half, then interleave the two halves.", "O(n)", "O(1)"],
  ["remove-nth-node-from-end-of-list", "Remove Nth Node From End of List", "M",
    "Two pointers n apart; when the lead pointer hits the end, the lag pointer is just before the target.", "O(n)", "O(1)"],
  ["copy-list-with-random-pointer", "Copy List with Random Pointer", "M",
    "Hash map from original → clone built in one pass; wire next and random pointers in a second pass.", "O(n)", "O(n)"],
  ["add-two-numbers", "Add Two Numbers", "M",
    "Grade-school addition walking both lists together with a carry digit.", "O(n)", "O(1)"],
  ["find-the-duplicate-number", "Find the Duplicate Number", "M",
    "Treat values as next-pointers and run Floyd's cycle detection; the cycle entrance is the duplicate.", "O(n)", "O(1)"],
  ["lru-cache", "LRU Cache", "M",
    "Hash map + doubly linked list: the map finds nodes in O(1), the list keeps recency order for O(1) eviction.", "O(1) per op", "O(n)"],
  ["merge-k-sorted-lists", "Merge k Sorted Lists", "H",
    "Min-heap of the k current heads: pop the smallest, append it, push its successor.", "O(n log k)", "O(k)"],
  ["reverse-nodes-in-k-group", "Reverse Nodes in k-Group", "H",
    "Count k nodes ahead, reverse that block in place, and stitch it onto the previous group.", "O(n)", "O(1)"],
]],
["Trees", [
  ["invert-binary-tree", "Invert Binary Tree", "E",
    "Swap the left and right children at every node, via DFS or BFS.", "O(n)", "O(h)"],
  ["maximum-depth-of-binary-tree", "Maximum Depth of Binary Tree", "E",
    "DFS: depth(node) = 1 + max(depth(left), depth(right)).", "O(n)", "O(h)"],
  ["diameter-of-binary-tree", "Diameter of Binary Tree", "E",
    "DFS returning subtree height while tracking the best left-height + right-height sum seen at any node.", "O(n)", "O(h)"],
  ["balanced-binary-tree", "Balanced Binary Tree", "E",
    "Bottom-up DFS returning height, short-circuiting −1 upward as soon as any subtree is unbalanced.", "O(n)", "O(h)"],
  ["same-tree", "Same Tree", "E",
    "Simultaneous DFS on both trees: values must match and both subtrees must be the same.", "O(n)", "O(h)"],
  ["subtree-of-another-tree", "Subtree of Another Tree", "E",
    "For each node of the main tree, run a same-tree comparison against the candidate subtree.", "O(n·m)", "O(h)"],
  ["lowest-common-ancestor-of-a-binary-search-tree", "Lowest Common Ancestor of a BST", "M",
    "Walk down from the root: go left/right while both nodes lie on the same side; the split point is the LCA.", "O(h)", "O(1)"],
  ["binary-tree-level-order-traversal", "Binary Tree Level Order Traversal", "M",
    "BFS with a queue, emitting one list of values per level.", "O(n)", "O(n)"],
  ["binary-tree-right-side-view", "Binary Tree Right Side View", "M",
    "BFS taking the last node of each level (or DFS visiting right first, keeping the first node per depth).", "O(n)", "O(n)"],
  ["count-good-nodes-in-binary-tree", "Count Good Nodes in Binary Tree", "M",
    "DFS carrying the maximum value on the path so far; a node counts if it is ≥ that maximum.", "O(n)", "O(h)"],
  ["validate-binary-search-tree", "Validate Binary Search Tree", "M",
    "DFS with (low, high) bounds that tighten at every step; each value must lie strictly inside its bounds.", "O(n)", "O(h)"],
  ["kth-smallest-element-in-a-bst", "Kth Smallest Element in a BST", "M",
    "In-order traversal visits a BST in sorted order; stop at the kth visited node.", "O(h+k)", "O(h)"],
  ["construct-binary-tree-from-preorder-and-inorder-traversal", "Construct Binary Tree from Preorder and Inorder Traversal", "M",
    "Preorder's first item is the root; split inorder around it (via an index map) and recurse on both sides.", "O(n)", "O(n)"],
  ["binary-tree-maximum-path-sum", "Binary Tree Maximum Path Sum", "H",
    "DFS returning the best downward gain; the best path through a node is node + left gain + right gain.", "O(n)", "O(h)"],
  ["serialize-and-deserialize-binary-tree", "Serialize and Deserialize Binary Tree", "H",
    "Preorder DFS with explicit null markers; deserialize by consuming tokens recursively in the same order.", "O(n)", "O(n)"],
]],
["Tries", [
  ["implement-trie-prefix-tree", "Implement Trie (Prefix Tree)", "M",
    "Nodes hold a children map and an end-of-word flag; insert/search walk character by character.", "O(k) per op", "O(Σ chars)"],
  ["design-add-and-search-words-data-structure", "Design Add and Search Words Data Structure", "M",
    "A trie where the wildcard '.' branches into every child via DFS.", "O(k) add", "O(Σ chars)"],
  ["word-search-ii", "Word Search II", "H",
    "Build a trie of all words, then DFS the board once, pruning any path that leaves the trie.", "O(m·n·4^k)", "O(Σ chars)"],
]],
["Heap / Priority Queue", [
  ["kth-largest-element-in-a-stream", "Kth Largest Element in a Stream", "E",
    "Keep a min-heap of size k; its root is always the kth largest element.", "O(log k) per add", "O(k)"],
  ["last-stone-weight", "Last Stone Weight", "E",
    "Max-heap: pop the two heaviest stones, push their difference, repeat until ≤ 1 stone remains.", "O(n log n)", "O(n)"],
  ["k-closest-points-to-origin", "K Closest Points to Origin", "M",
    "Max-heap of size k keyed on distance — or quickselect for O(n) average.", "O(n log k)", "O(k)"],
  ["kth-largest-element-in-an-array", "Kth Largest Element in an Array", "M",
    "Quickselect: partition around a pivot and recurse into only the side containing the answer.", "O(n) avg", "O(1)"],
  ["task-scheduler", "Task Scheduler", "M",
    "Greedy on the most frequent task: intervals = max(n_tasks, (maxFreq−1)·(cooldown+1) + ties).", "O(n)", "O(26)"],
  ["design-twitter", "Design Twitter", "M",
    "Per-user tweet lists with global timestamps; merge the newest tweets across followees with a heap.", "O(k log k)", "O(n)"],
  ["find-median-from-data-stream", "Find Median from Data Stream", "H",
    "Two heaps: a max-heap of the lower half and a min-heap of the upper half, kept balanced in size.", "O(log n) add", "O(n)"],
]],
["Backtracking", [
  ["subsets", "Subsets", "M",
    "DFS choosing include / exclude for each element; every leaf is one subset.", "O(n·2ⁿ)", "O(n)"],
  ["combination-sum", "Combination Sum", "M",
    "DFS either reusing the current candidate or moving past it; prune when the remaining target goes negative.", "O(2^t)", "O(t)"],
  ["permutations", "Permutations", "M",
    "DFS choosing each unused element for the current position and backtracking.", "O(n·n!)", "O(n)"],
  ["subsets-ii", "Subsets II", "M",
    "Sort first, then DFS skipping equal siblings at the same depth to avoid duplicate subsets.", "O(n·2ⁿ)", "O(n)"],
  ["combination-sum-ii", "Combination Sum II", "M",
    "Sort; DFS using each candidate at most once and skipping duplicates at the same depth.", "O(2ⁿ)", "O(n)"],
  ["word-search", "Word Search", "M",
    "DFS from every cell, marking cells visited in place and un-marking on backtrack.", "O(m·n·4^k)", "O(k)"],
  ["palindrome-partitioning", "Palindrome Partitioning", "M",
    "DFS cutting the string at every palindromic prefix and recursing on the rest.", "O(n·2ⁿ)", "O(n)"],
  ["letter-combinations-of-a-phone-number", "Letter Combinations of a Phone Number", "M",
    "DFS appending each letter mapped to the current digit, one digit per depth.", "O(n·4ⁿ)", "O(n)"],
  ["n-queens", "N-Queens", "H",
    "Backtrack row by row, with hash sets for used columns and both diagonal directions.", "O(n!)", "O(n)"],
]],
["Graphs", [
  ["number-of-islands", "Number of Islands", "M",
    "Scan the grid; each unvisited '1' starts a BFS/DFS flood fill and counts as one island.", "O(m·n)", "O(m·n)"],
  ["clone-graph", "Clone Graph", "M",
    "DFS/BFS with a hash map original → clone so cycles and shared nodes are handled once.", "O(V+E)", "O(V)"],
  ["max-area-of-island", "Max Area of Island", "M",
    "Flood-fill each island, returning its cell count, and keep the maximum.", "O(m·n)", "O(m·n)"],
  ["pacific-atlantic-water-flow", "Pacific Atlantic Water Flow", "M",
    "Reverse-DFS inland (uphill) from each ocean's border cells; the answer is cells reached by both oceans.", "O(m·n)", "O(m·n)"],
  ["surrounded-regions", "Surrounded Regions", "M",
    "DFS from border 'O's to mark unsurroundable cells, then flip every other 'O' to 'X'.", "O(m·n)", "O(m·n)"],
  ["rotting-oranges", "Rotting Oranges", "M",
    "Multi-source BFS starting from all rotten oranges at once, counting minutes per BFS layer.", "O(m·n)", "O(m·n)"],
  ["walls-and-gates", "Walls and Gates", "M",
    "Multi-source BFS from every gate; the first visit to a room writes its shortest distance.", "O(m·n)", "O(m·n)"],
  ["course-schedule", "Course Schedule", "M",
    "Cycle detection on the prerequisite graph — DFS with three colors, or Kahn's topological sort.", "O(V+E)", "O(V+E)"],
  ["course-schedule-ii", "Course Schedule II", "M",
    "Kahn's algorithm: repeatedly take courses with in-degree 0; a complete order means no cycle.", "O(V+E)", "O(V+E)"],
  ["redundant-connection", "Redundant Connection", "M",
    "Union-Find: the first edge whose two endpoints are already connected is the redundant one.", "O(n·α(n))", "O(n)"],
  ["number-of-connected-components-in-an-undirected-graph", "Number of Connected Components in an Undirected Graph", "M",
    "Union-Find over the edges (or DFS from each unvisited node); count the remaining roots.", "O(E·α(n))", "O(n)"],
  ["graph-valid-tree", "Graph Valid Tree", "M",
    "A valid tree has exactly n−1 edges and is fully connected — check with Union-Find or one DFS.", "O(E·α(n))", "O(n)"],
  ["word-ladder", "Word Ladder", "H",
    "BFS over words connected by one-letter wildcard buckets (h*t), counting layers to the target.", "O(n·k²)", "O(n·k)"],
]],
["Advanced Graphs", [
  ["reconstruct-itinerary", "Reconstruct Itinerary", "H",
    "Hierholzer's algorithm for an Eulerian path, always taking the lexicographically smallest unused edge.", "O(E log E)", "O(E)"],
  ["min-cost-to-connect-all-points", "Min Cost to Connect All Points", "M",
    "Prim's minimum spanning tree: grow from any point, always adding the cheapest edge to a new point.", "O(n²)", "O(n)"],
  ["network-delay-time", "Network Delay Time", "M",
    "Dijkstra from the source; the answer is the largest shortest-path distance (or −1 if unreachable).", "O(E log V)", "O(V+E)"],
  ["swim-in-rising-water", "Swim in Rising Water", "H",
    "Dijkstra-style search where a path's cost is its maximum cell value (or binary search + BFS).", "O(n² log n)", "O(n²)"],
  ["alien-dictionary", "Alien Dictionary", "H",
    "Derive precedence edges from each adjacent word pair's first differing letter, then topologically sort.", "O(Σ chars)", "O(1)"],
  ["cheapest-flights-within-k-stops", "Cheapest Flights Within K Stops", "M",
    "Bellman-Ford limited to k+1 relaxation rounds, relaxing from a snapshot of the previous round.", "O(k·E)", "O(V)"],
]],
["1-D Dynamic Programming", [
  ["climbing-stairs", "Climbing Stairs", "E",
    "Fibonacci: ways(n) = ways(n−1) + ways(n−2), kept in two rolling variables.", "O(n)", "O(1)"],
  ["min-cost-climbing-stairs", "Min Cost Climbing Stairs", "E",
    "dp[i] = cost[i] + min(dp[i+1], dp[i+2]), rolled into two variables from the end.", "O(n)", "O(1)"],
  ["house-robber", "House Robber", "M",
    "dp: best(i) = max(best(i−1), best(i−2) + nums[i]), kept in two rolling variables.", "O(n)", "O(1)"],
  ["house-robber-ii", "House Robber II", "M",
    "Run House Robber twice on the circle: once excluding the first house, once excluding the last.", "O(n)", "O(1)"],
  ["longest-palindromic-substring", "Longest Palindromic Substring", "M",
    "Expand around all 2n−1 centers (odd and even), tracking the longest successful expansion.", "O(n²)", "O(1)"],
  ["palindromic-substrings", "Palindromic Substrings", "M",
    "Expand around every center and count each successful expansion step.", "O(n²)", "O(1)"],
  ["decode-ways", "Decode Ways", "M",
    "dp over positions: add ways(i+1) for a valid single digit and ways(i+2) for a valid two-digit pair.", "O(n)", "O(1)"],
  ["coin-change", "Coin Change", "M",
    "Bottom-up dp over amounts: dp[a] = 1 + min(dp[a − coin]) across all coins.", "O(amount·coins)", "O(amount)"],
  ["maximum-product-subarray", "Maximum Product Subarray", "M",
    "Track the running maximum AND minimum products at each element — a negative number swaps them.", "O(n)", "O(1)"],
  ["word-break", "Word Break", "M",
    "dp[i] is true if some dictionary word matches s starting at i and dp[i + len] is true.", "O(n²·k)", "O(n)"],
  ["longest-increasing-subsequence", "Longest Increasing Subsequence", "M",
    "Patience sorting: keep an array of minimal pile tops and binary search each number's pile.", "O(n log n)", "O(n)"],
  ["partition-equal-subset-sum", "Partition Equal Subset Sum", "M",
    "Subset-sum dp targeting half the total, using a set (or bitset) of reachable sums.", "O(n·sum)", "O(sum)"],
]],
["2-D Dynamic Programming", [
  ["unique-paths", "Unique Paths", "M",
    "Each cell's paths = paths from above + paths from the left; roll the dp into a single row.", "O(m·n)", "O(n)"],
  ["longest-common-subsequence", "Longest Common Subsequence", "M",
    "Grid dp: on a character match take 1 + diagonal, otherwise the max of up and left.", "O(m·n)", "O(m·n)"],
  ["best-time-to-buy-and-sell-stock-with-cooldown", "Best Time to Buy and Sell Stock with Cooldown", "M",
    "State-machine dp per day: holding, just sold (cooldown), and free-to-buy states.", "O(n)", "O(1)"],
  ["coin-change-ii", "Coin Change II", "M",
    "Count combinations: iterate coins in the outer loop so each combination is counted once — dp[a] += dp[a−coin].", "O(amount·coins)", "O(amount)"],
  ["target-sum", "Target Sum", "M",
    "Reduce to counting subsets that sum to (total + target) / 2, solved with subset-sum dp.", "O(n·sum)", "O(sum)"],
  ["interleaving-string", "Interleaving String", "M",
    "dp[i][j]: can s3's first i+j chars be built from s1[:i] and s2[:j]? Take a char from either on a match.", "O(m·n)", "O(n)"],
  ["longest-increasing-path-in-a-matrix", "Longest Increasing Path in a Matrix", "H",
    "DFS + memoization per cell: a cell's answer is 1 + the best among strictly larger neighbors.", "O(m·n)", "O(m·n)"],
  ["distinct-subsequences", "Distinct Subsequences", "H",
    "dp counting ways: on a match add use-both and skip-s ways; otherwise carry skip-s ways.", "O(m·n)", "O(n)"],
  ["edit-distance", "Edit Distance", "M",
    "Grid dp: equal chars take the diagonal; otherwise 1 + min(insert, delete, replace).", "O(m·n)", "O(n)"],
  ["burst-balloons", "Burst Balloons", "H",
    "Interval dp choosing the LAST balloon to burst in each range, so its neighbors are the range borders.", "O(n³)", "O(n²)"],
  ["regular-expression-matching", "Regular Expression Matching", "H",
    "dp over (i, j) pairs where '*' means zero-or-more of the preceding element.", "O(m·n)", "O(m·n)"],
]],
["Greedy", [
  ["maximum-subarray", "Maximum Subarray", "M",
    "Kadane's algorithm: extend the running sum, but restart at the current number once the sum goes negative.", "O(n)", "O(1)"],
  ["jump-game", "Jump Game", "M",
    "Scan left to right tracking the furthest reachable index; fail if the scan passes it.", "O(n)", "O(1)"],
  ["jump-game-ii", "Jump Game II", "M",
    "BFS-like layers: within the current reach, compute the furthest next reach; each layer is one jump.", "O(n)", "O(1)"],
  ["gas-station", "Gas Station", "M",
    "If total gas ≥ total cost a start exists; move the candidate start forward whenever the running tank goes negative.", "O(n)", "O(1)"],
  ["hand-of-straights", "Hand of Straights", "M",
    "Count cards; repeatedly build one straight starting from the smallest remaining card.", "O(n log n)", "O(n)"],
  ["merge-triplets-to-form-target-triplet", "Merge Triplets to Form Target Triplet", "M",
    "Discard triplets exceeding the target anywhere; check that each target coordinate is achieved by a survivor.", "O(n)", "O(1)"],
  ["partition-labels", "Partition Labels", "M",
    "Record each letter's last index; extend the current partition to the furthest last-index seen, cut when reached.", "O(n)", "O(26)"],
  ["valid-parenthesis-string", "Valid Parenthesis String", "M",
    "Track a range [lo, hi] of possible open-bracket counts; '*' widens the range; valid if lo can reach 0.", "O(n)", "O(1)"],
]],
["Intervals", [
  ["insert-interval", "Insert Interval", "M",
    "Emit intervals ending before the new one, merge everything overlapping it, then append the rest.", "O(n)", "O(n)"],
  ["merge-intervals", "Merge Intervals", "M",
    "Sort by start; merge each interval into the last output interval when they overlap.", "O(n log n)", "O(n)"],
  ["non-overlapping-intervals", "Non-overlapping Intervals", "M",
    "Sort by end; greedily keep intervals starting after the last kept end, count the rest as removed.", "O(n log n)", "O(1)"],
  ["meeting-rooms", "Meeting Rooms", "E",
    "Sort by start; any meeting that starts before the previous one ends is a conflict.", "O(n log n)", "O(1)"],
  ["meeting-rooms-ii", "Meeting Rooms II", "M",
    "Sort starts and ends separately; sweep through time counting concurrent meetings.", "O(n log n)", "O(n)"],
  ["minimum-interval-to-include-each-query", "Minimum Interval to Include Each Query", "H",
    "Sort intervals and queries; sweep queries with a min-heap keyed by interval size, evicting expired intervals.", "O((n+q) log n)", "O(n)"],
]],
["Math & Geometry", [
  ["rotate-image", "Rotate Image", "M",
    "Transpose the matrix, then reverse every row — a 90° clockwise rotation in place.", "O(n²)", "O(1)"],
  ["spiral-matrix", "Spiral Matrix", "M",
    "Peel layers with four moving boundaries (top, bottom, left, right), shrinking after each side.", "O(m·n)", "O(1)"],
  ["set-matrix-zeroes", "Set Matrix Zeroes", "M",
    "Use the first row and column as the zero markers themselves to reach O(1) extra space.", "O(m·n)", "O(1)"],
  ["happy-number", "Happy Number", "E",
    "Floyd cycle detection on the digit-square-sum sequence — happy numbers reach 1, others cycle.", "O(log n)", "O(1)"],
  ["plus-one", "Plus One", "E",
    "Add from the last digit with a carry; prepend a 1 if the carry survives past the front.", "O(n)", "O(1)"],
  ["powx-n", "Pow(x, n)", "M",
    "Fast exponentiation: square the base and halve the exponent each step.", "O(log n)", "O(1)"],
  ["multiply-strings", "Multiply Strings", "M",
    "Grade-school multiplication into a digit array: digit i × digit j accumulates at position i + j + 1.", "O(m·n)", "O(m+n)"],
  ["detect-squares", "Detect Squares", "M",
    "Count stored points; for each stored diagonal candidate of a query, multiply the two corner counts.", "O(n) per query", "O(n)"],
]],
["Bit Manipulation", [
  ["single-number", "Single Number", "E",
    "XOR every number together; pairs cancel out and the single number survives.", "O(n)", "O(1)"],
  ["number-of-1-bits", "Number of 1 Bits", "E",
    "Repeatedly clear the lowest set bit with n & (n−1), counting iterations.", "O(set bits)", "O(1)"],
  ["counting-bits", "Counting Bits", "E",
    "dp: bits(i) = bits(i >> 1) + (i & 1) — reuse the already-computed half.", "O(n)", "O(n)"],
  ["reverse-bits", "Reverse Bits", "E",
    "Build the result bit by bit: shift the result left, append n's low bit, shift n right, 32 times.", "O(32)", "O(1)"],
  ["missing-number", "Missing Number", "E",
    "XOR all indices 0..n with all values; everything cancels except the missing number.", "O(n)", "O(1)"],
  ["sum-of-two-integers", "Sum of Two Integers", "M",
    "Add without '+': XOR gives the partial sum, AND shifted left gives the carry; loop until the carry is 0.", "O(1)", "O(1)"],
  ["reverse-integer", "Reverse Integer", "M",
    "Pop digits with mod 10 and push onto the result, checking 32-bit overflow before every push.", "O(log n)", "O(1)"],
]],
];

// Flat lookup by slug.
const PROBLEMS = {};
DATA.forEach(([cat, items]) => {
  items.forEach(([slug, title, diff, approach, time, space]) => {
    PROBLEMS[slug] = { slug, title, diff, approach, time, space, cat };
  });
});
