// Concise problem statements (original summaries), keyed by slug.
const STATEMENTS = {
// Arrays & Hashing
"contains-duplicate": "Given an integer array nums, return true if any value appears more than once, or false if every element is distinct.",
"valid-anagram": "Given two strings s and t, return true if t is an anagram of s — it uses exactly the same characters with the same frequencies.",
"two-sum": "Given an array of integers nums and an integer target, return the indices of the two numbers that add up to target. Exactly one solution exists, and the same element cannot be used twice.",
"group-anagrams": "Given an array of strings, group the words that are anagrams of each other and return the groups.",
"top-k-frequent-elements": "Given an integer array nums and an integer k, return the k elements that occur most frequently.",
"encode-and-decode-strings": "Design an encode function that turns a list of strings into one single string, and a decode function that recovers the original list — regardless of what characters the strings contain.",
"product-of-array-except-self": "Given an integer array nums, return an array where answer[i] is the product of every element except nums[i] — in O(n) time and without using division.",
"valid-sudoku": "Given a partially filled 9×9 Sudoku board, decide whether the filled cells are valid: no digit repeats within any row, any column, or any 3×3 box.",
"longest-consecutive-sequence": "Given an unsorted array of integers, return the length of the longest run of consecutive values (e.g. 1, 2, 3, 4) — in O(n) time.",
// Two Pointers
"valid-palindrome": "Given a string s, return true if it reads the same forwards and backwards after keeping only alphanumeric characters and ignoring case.",
"two-sum-ii-input-array-is-sorted": "Given a 1-indexed array sorted in ascending order and a target, return the 1-based indices of the two numbers that add up to the target, using only constant extra space.",
"3sum": "Given an integer array, return all unique triplets [a, b, c] such that a + b + c = 0.",
"container-with-most-water": "Given an array of vertical wall heights, choose two walls that together with the x-axis contain the most water, and return that maximum area.",
"trapping-rain-water": "Given an elevation map as an array of bar heights, compute how much rain water would be trapped between the bars.",
// Sliding Window
"best-time-to-buy-and-sell-stock": "Given an array of daily stock prices, pick one day to buy and a later day to sell so profit is maximized; return that profit, or 0 if no profit is possible.",
"longest-substring-without-repeating-characters": "Given a string s, return the length of the longest substring that contains no repeated characters.",
"longest-repeating-character-replacement": "Given a string s and an integer k, you may change at most k characters; return the length of the longest substring that can be turned into all one letter.",
"permutation-in-string": "Given strings s1 and s2, return true if s2 contains a permutation of s1 as a contiguous substring.",
"minimum-window-substring": "Given strings s and t, return the smallest substring of s that contains every character of t (including duplicates), or the empty string if none exists.",
"sliding-window-maximum": "Given an array and a window size k, return the maximum of each contiguous window of size k as it slides across the array.",
// Stack
"valid-parentheses": "Given a string containing only the brackets ( ) [ ] { }, decide whether it is valid: every opener is closed by the matching bracket in the correct order.",
"min-stack": "Design a stack that supports push, pop, top, and retrieving the minimum element — each in O(1) time.",
"evaluate-reverse-polish-notation": "Evaluate an arithmetic expression given in Reverse Polish (postfix) notation with the operators + − × ÷.",
"generate-parentheses": "Given n pairs of parentheses, generate every well-formed (balanced) combination.",
"daily-temperatures": "Given daily temperatures, return for each day how many days you must wait for a warmer temperature, or 0 if none ever comes.",
"car-fleet": "Cars at given positions drive at given speeds toward a target and cannot pass each other; a car that catches up joins a fleet. Return how many fleets arrive at the target.",
"largest-rectangle-in-histogram": "Given a histogram's bar heights (all bars of width 1), return the area of the largest rectangle that fits entirely within the bars.",
// Binary Search
"binary-search": "Given a sorted integer array and a target, return the target's index, or -1 if it is absent — in O(log n) time.",
"search-a-2d-matrix": "Given a matrix whose rows are sorted and where each row starts after the previous row ends, decide whether a target value exists in it.",
"koko-eating-bananas": "Koko must finish all banana piles within h hours, eating from one pile per hour at a fixed speed k; return the minimum k that lets her finish in time.",
"find-minimum-in-rotated-sorted-array": "A sorted array of unique values has been rotated an unknown number of positions; find its minimum element in O(log n) time.",
"search-in-rotated-sorted-array": "A sorted array of unique values has been rotated at an unknown pivot; return the index of a target value in O(log n) time, or -1.",
"time-based-key-value-store": "Design a store where set(key, value, timestamp) records values over time and get(key, timestamp) returns the value stored at the largest timestamp ≤ the query.",
"median-of-two-sorted-arrays": "Given two sorted arrays, return the median of all their elements combined, in O(log(min(m, n))) time.",
// Linked List
"reverse-linked-list": "Given the head of a singly linked list, reverse the list and return the new head.",
"merge-two-sorted-lists": "Merge two sorted linked lists into one sorted list by splicing their nodes together, and return its head.",
"linked-list-cycle": "Given the head of a linked list, determine whether following next pointers ever loops back — that is, whether the list contains a cycle.",
"reorder-list": "Reorder a list L0→L1→…→Ln into L0→Ln→L1→Ln−1→… in place, without changing any node values.",
"remove-nth-node-from-end-of-list": "Remove the nth node from the end of a linked list in a single pass and return the head.",
"copy-list-with-random-pointer": "Each node of a list has an extra random pointer to any node (or null); return a deep copy of the entire list.",
"add-two-numbers": "Two non-negative integers are stored digit-by-digit in reverse order in two linked lists; add them and return the sum as a linked list.",
"find-the-duplicate-number": "An array of n + 1 integers holds values in the range [1, n], so at least one value repeats; find it without modifying the array and using O(1) space.",
"lru-cache": "Design a fixed-capacity Least-Recently-Used cache with O(1) get and put, evicting the least recently used entry when capacity is exceeded.",
"merge-k-sorted-lists": "Merge k sorted linked lists into one sorted linked list and return it.",
"reverse-nodes-in-k-group": "Reverse a linked list k nodes at a time; any nodes left over at the end (fewer than k) keep their original order.",
// Trees
"invert-binary-tree": "Given the root of a binary tree, invert it (mirror it left-to-right) and return the root.",
"maximum-depth-of-binary-tree": "Return the number of nodes on the longest path from the root down to the farthest leaf.",
"diameter-of-binary-tree": "Return the length in edges of the longest path between any two nodes in a binary tree; the path need not pass through the root.",
"balanced-binary-tree": "Decide whether a binary tree is height-balanced: at every node, the heights of the two subtrees differ by at most 1.",
"same-tree": "Given the roots of two binary trees, decide whether the trees are structurally identical with equal node values.",
"subtree-of-another-tree": "Given trees root and subRoot, decide whether some subtree of root is identical to subRoot.",
"lowest-common-ancestor-of-a-binary-search-tree": "Given a BST and two of its nodes, return their lowest common ancestor — the deepest node that has both as descendants (a node may be its own descendant).",
"binary-tree-level-order-traversal": "Return the values of a binary tree level by level from top to bottom, as a list of lists.",
"binary-tree-right-side-view": "Return the values visible when looking at a binary tree from the right side, top to bottom — the rightmost node of each level.",
"count-good-nodes-in-binary-tree": "A node is good if no node on the path from the root to it has a greater value; count the good nodes in the tree.",
"validate-binary-search-tree": "Decide whether a binary tree is a valid BST: every node is greater than everything in its left subtree and less than everything in its right subtree.",
"kth-smallest-element-in-a-bst": "Given a BST and an integer k, return the kth smallest value in the tree.",
"construct-binary-tree-from-preorder-and-inorder-traversal": "Rebuild a binary tree from its preorder and inorder traversals and return its root.",
"binary-tree-maximum-path-sum": "A path is any sequence of connected nodes, each used at most once; return the maximum possible sum of node values along any path.",
"serialize-and-deserialize-binary-tree": "Design functions to serialize a binary tree to a string and deserialize that string back into the identical tree.",
// Tries
"implement-trie-prefix-tree": "Implement a trie (prefix tree) supporting insert(word), search(word), and startsWith(prefix).",
"design-add-and-search-words-data-structure": "Design a structure with addWord(word) and search(word), where searches may use '.' as a wildcard matching any single letter.",
"word-search-ii": "Given a board of letters and a list of words, return every word that can be traced through horizontally/vertically adjacent cells without reusing a cell.",
// Heap / Priority Queue
"kth-largest-element-in-a-stream": "Design a class initialized with k and a stream of numbers, where each add(val) returns the kth largest value seen so far.",
"last-stone-weight": "Repeatedly smash the two heaviest stones together — equal stones both shatter, unequal ones leave their difference; return the weight of the last stone, or 0.",
"k-closest-points-to-origin": "Given points on a plane and an integer k, return the k points closest to the origin.",
"kth-largest-element-in-an-array": "Given an unsorted array and an integer k, return the kth largest element without fully sorting the array.",
"task-scheduler": "Given tasks (letters) and a cooldown n required between two identical tasks, return the minimum number of CPU time units to finish all tasks.",
"design-twitter": "Design a simplified Twitter: post tweets, follow and unfollow users, and fetch the 10 most recent tweets across a user's own posts and followees.",
"find-median-from-data-stream": "Design a structure that accepts a stream of numbers and can return the median of all elements seen so far at any moment.",
// Backtracking
"subsets": "Given an array of distinct integers, return every possible subset — the power set.",
"combination-sum": "Given distinct candidates and a target, return all unique combinations that sum to the target; each candidate may be reused any number of times.",
"permutations": "Given an array of distinct integers, return every possible ordering (permutation) of its elements.",
"subsets-ii": "Given an array that may contain duplicates, return all possible subsets without producing any duplicate subsets.",
"combination-sum-ii": "Given candidates (which may repeat) and a target, return all unique combinations summing to the target, using each candidate at most once.",
"word-search": "Given a grid of letters and a word, decide whether the word can be traced through horizontally/vertically adjacent cells without reusing a cell.",
"palindrome-partitioning": "Split a string in every possible way such that every piece is a palindrome; return all such partitions.",
"letter-combinations-of-a-phone-number": "Given a string of digits 2–9, return every letter combination they could spell on a phone keypad.",
"n-queens": "Place n queens on an n×n chessboard so that no two attack each other; return every distinct arrangement.",
// Graphs
"number-of-islands": "Given a grid of '1' (land) and '0' (water), count the islands — maximal groups of land cells connected horizontally or vertically.",
"clone-graph": "Given a reference node of a connected undirected graph, return a deep copy of the entire graph.",
"max-area-of-island": "Given a binary grid, return the area (number of cells) of the largest island, or 0 if there is no land.",
"pacific-atlantic-water-flow": "On a height grid whose top/left edges touch the Pacific and bottom/right the Atlantic, water flows to equal-or-lower neighbors; return all cells from which water can reach both oceans.",
"surrounded-regions": "On a board of 'X' and 'O', flip to 'X' every region of 'O's that is completely surrounded — i.e. touches no border cell.",
"rotting-oranges": "In a grid of empty cells, fresh oranges, and rotten oranges, rot spreads to adjacent fresh oranges each minute; return the minutes until nothing is fresh, or -1 if some orange can never rot.",
"walls-and-gates": "In a grid of walls, gates, and empty rooms, fill every room with the distance to its nearest gate, leaving it as infinity if no gate is reachable.",
"course-schedule": "Given a number of courses and prerequisite pairs, decide whether it is possible to finish every course — i.e. the prerequisite graph contains no cycle.",
"course-schedule-ii": "Given courses and prerequisite pairs, return any valid order in which all courses can be taken, or an empty list if none exists.",
"redundant-connection": "A tree with one extra edge added is given as an edge list; return the edge that can be removed to restore a tree (choosing the last such edge in the input).",
"number-of-connected-components-in-an-undirected-graph": "Given n nodes and a list of undirected edges, return the number of connected components in the graph.",
"graph-valid-tree": "Given n nodes and a list of undirected edges, decide whether they form a valid tree — connected and containing no cycle.",
"word-ladder": "Given beginWord, endWord, and a word list, return the length of the shortest transformation sequence that changes one letter at a time with every intermediate word in the list, or 0.",
// Advanced Graphs
"reconstruct-itinerary": "Given airline tickets as [from, to] pairs, reconstruct the itinerary that uses every ticket exactly once, starts at JFK, and is lexicographically smallest.",
"min-cost-to-connect-all-points": "Given points on a plane, where connecting two points costs their Manhattan distance, return the minimum total cost to connect every point.",
"network-delay-time": "A signal leaves node k and travels along weighted directed edges; return the time for it to reach all nodes, or -1 if some node is unreachable.",
"swim-in-rising-water": "Water rises one unit per time step over a grid of elevations; you may move between adjacent cells once both are underwater. Return the earliest time to travel from top-left to bottom-right.",
"alien-dictionary": "Given a list of words sorted according to an unknown alphabet, recover a valid ordering of that alphabet's letters, or report that none exists.",
"cheapest-flights-within-k-stops": "Given flights with prices, a source, a destination, and a maximum of k stops, return the cheapest price to make the trip, or -1.",
// 1-D DP
"climbing-stairs": "You climb a staircase of n steps, taking 1 or 2 steps at a time; return how many distinct ways there are to reach the top.",
"min-cost-climbing-stairs": "Each stair has a cost paid when you step on it; starting from step 0 or 1 and climbing 1–2 stairs at a time, return the cheapest total cost to pass the top.",
"house-robber": "Houses along a street hold money, but adjacent houses share an alarm; return the maximum you can rob without robbing two adjacent houses.",
"house-robber-ii": "Same as House Robber, except the houses form a circle — the first and last houses are adjacent.",
"longest-palindromic-substring": "Given a string s, return its longest contiguous substring that is a palindrome.",
"palindromic-substrings": "Count how many substrings of s are palindromes, counting each occurrence separately.",
"decode-ways": "Digits map to letters (1→A … 26→Z); given a digit string, count how many different ways it can be decoded.",
"coin-change": "Given coin denominations and a target amount, return the fewest coins needed to make the amount exactly, or -1 if it cannot be made.",
"maximum-product-subarray": "Given an integer array, return the largest product of any contiguous subarray.",
"word-break": "Given a string and a dictionary of words, decide whether the string can be segmented into a sequence of dictionary words (reuse allowed).",
"longest-increasing-subsequence": "Return the length of the longest strictly increasing subsequence of the array — elements keep their order but need not be adjacent.",
"partition-equal-subset-sum": "Decide whether the array can be split into two subsets whose sums are equal.",
// 2-D DP
"unique-paths": "A robot on an m×n grid starts at the top-left and moves only right or down; count the distinct paths to the bottom-right corner.",
"longest-common-subsequence": "Given two strings, return the length of their longest common subsequence — characters in order but not necessarily contiguous.",
"best-time-to-buy-and-sell-stock-with-cooldown": "Trade a stock with unlimited transactions, but after selling you must cool down for one day before buying again; return the maximum profit.",
"coin-change-ii": "Given coin denominations and an amount, count the number of distinct combinations of coins that make the amount.",
"target-sum": "Assign + or − to every number in the array; count how many assignments make the expression equal the target.",
"interleaving-string": "Decide whether s3 can be formed by interleaving s1 and s2 while preserving the character order within each.",
"longest-increasing-path-in-a-matrix": "Return the length of the longest strictly increasing path in a matrix, moving up, down, left, or right.",
"distinct-subsequences": "Count how many distinct subsequences of s equal t.",
"edit-distance": "Return the minimum number of single-character insertions, deletions, or replacements needed to turn one word into another.",
"burst-balloons": "Bursting balloon i earns nums[left] × nums[i] × nums[right] for its current neighbors; choose the bursting order that maximizes the total coins.",
"regular-expression-matching": "Implement regular-expression matching over the full string, where '.' matches any character and '*' means zero or more of the preceding element.",
// Greedy
"maximum-subarray": "Given an integer array, return the largest possible sum of a contiguous subarray.",
"jump-game": "Each element is the maximum jump length from that index; starting at index 0, decide whether the last index is reachable.",
"jump-game-ii": "Each element is the maximum jump length from that index; return the minimum number of jumps needed to reach the last index.",
"gas-station": "Stations on a circular route provide gas[i] fuel and cost cost[i] to reach the next; return the starting station from which a full lap is possible, or -1.",
"hand-of-straights": "Decide whether the cards can be rearranged into groups of exactly groupSize consecutive values.",
"merge-triplets-to-form-target-triplet": "You may repeatedly merge two triplets by taking their element-wise maxima; decide whether some sequence of merges can produce exactly the target triplet.",
"partition-labels": "Split a string into as many parts as possible so that no letter appears in two different parts; return the sizes of the parts.",
"valid-parenthesis-string": "Given a string of '(', ')' and '*', where '*' may act as '(', ')', or nothing, decide whether it can be a valid parenthesis string.",
// Intervals
"insert-interval": "Given sorted, non-overlapping intervals and a new interval, insert it and merge as needed so the result is again sorted and non-overlapping.",
"merge-intervals": "Given a list of intervals, merge every group of overlapping intervals and return the merged list.",
"non-overlapping-intervals": "Return the minimum number of intervals to remove so that the remaining intervals do not overlap.",
"meeting-rooms": "Given meeting time intervals, decide whether one person could attend all of them — i.e. none overlap.",
"meeting-rooms-ii": "Given meeting time intervals, return the minimum number of conference rooms required to hold them all.",
"minimum-interval-to-include-each-query": "For each query point, return the size of the smallest interval that contains it, or -1 if no interval does.",
// Math & Geometry
"rotate-image": "Rotate an n×n matrix 90 degrees clockwise, in place.",
"spiral-matrix": "Return all elements of a matrix in clockwise spiral order.",
"set-matrix-zeroes": "If any cell of the matrix is 0, set its entire row and column to 0 — in place.",
"happy-number": "Repeatedly replace a number with the sum of the squares of its digits; return true if the process reaches 1 rather than looping forever.",
"plus-one": "A large integer is given as an array of its digits; add one to it and return the resulting digits.",
"powx-n": "Implement pow(x, n): compute x raised to the integer power n, handling negative exponents.",
"multiply-strings": "Multiply two non-negative integers given as strings and return the product as a string, without converting the inputs to numbers directly.",
"detect-squares": "Design a structure that adds points to a plane and, for a query point, counts the axis-aligned squares it forms with previously added points.",
// Bit Manipulation
"single-number": "Every element of the array appears exactly twice except one; find that single element in O(n) time and O(1) space.",
"number-of-1-bits": "Return the number of set bits (1s) in the binary representation of an unsigned integer.",
"counting-bits": "For every i from 0 to n, compute how many 1 bits i has, in O(n) total time.",
"reverse-bits": "Reverse the 32 bits of an unsigned integer and return the resulting number.",
"missing-number": "An array contains n distinct numbers taken from the range [0, n]; return the one number in the range that is missing.",
"sum-of-two-integers": "Compute the sum of two integers without using the + or − operators.",
"reverse-integer": "Reverse the digits of a signed 32-bit integer, returning 0 if the reversed value overflows the 32-bit range.",
};
